# Generated by Django 5.1.6 on 2025-02-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_options_task_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
    ]
